# Generated by Django 4.1.5 on 2023-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='date',
            field=models.DateField(default='2000-11-22'),
            preserve_default=False,
        ),
    ]
